builds:
  - main: ./cmd/getmoe
    binary: getmoe
    goarch:
      - 386
      - amd64
    goos:
      - windows
      - darwin
      - linux
    env:
      - CGO_ENABLED=0
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - typo
      - Merge pull request
      - Merge branch
archive:
  replacements:
    darwin: macOS
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
scoop:
  bucket:
    owner: leonidboykov
    name: scoop-bucket
  homepage: https://github.com/leonidboykov/getmoe
  description: cli tool for boorus
  license: MIT
