[prune]
  unused-packages = true
  go-tests = true

[[constraint]]
  name = "github.com/imdario/mergo"
  version = "0.3.4"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"
